## Smart Logistics Management & Analytics Platform
### 1. Introduction
#### 1.1 Problem Statement
+ In modern logistics operations, global courier companies such as DHL and FedEx manage thousands of shipments daily across multiple routes, warehouses, and courier personnel.
+ With increasing shipment volumes and operational complexity, logistics networks generate large amounts of data from multiple sources, including shipment records, tracking updates, cost sheets, route details, and warehouse information.
+ These datasets often exist in different formats such as CSV and JSON files, making centralized analysis challenging.
+ Operational inefficiencies such as delivery delays, high transportation costs, underutilized warehouses, and inconsistent courier performance can significantly impact profitability and customer satisfaction.
+ Without an integrated analytics system, management faces difficulties in:
    - Monitoring delivery performance
    - Identifying bottleneck routes
    - Tracking real-time shipment status
    - Analyzing operational costs
    - Evaluating courier efficiency
    - Detecting cancellation and delay patterns
+ The lack of a unified data platform restricts visibility, reduces operational transparency, and limits data-driven decision-making.
#### 1.2 Objectives
+ The objective of this project is to develop a centralized Smart Logistics Management & Analytics Platform that integrates multi-source operational data into a structured MySQL database and provides an interactive Streamlit dashboard for real-time performance monitoring and business intelligence analysis.
+ The system aims to:
    - Consolidate shipment, tracking, cost, courier, route, and warehouse data
    - Design a relational database schema for efficient storage and querying
    - Calculate key performance indicators (KPIs) for operational evaluation
    - Provide interactive visualizations for management insights
    - Support data-driven decision-making for logistics optimization

### 2. Data Profiling

#### 2.1 Import Required Libraries
+ To process, analyze, and visualize the logistics datasets, the following Python libraries are imported:
    - Pandas – For data loading, cleaning, and manipulation
    - JSON – For handling JSON formatted files
    - Matplotlib – For basic data visualization
    - Seaborn – For advanced statistical visualizations
    - Streamlit – To build the interactive dashboard
    - Datetime – To handle and convert date/time columns

In [ ]:
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from datetime import datetime
import mysql.connector
from sqlalchemy import create_engine

#### 2.2 Load JSON Files

In [ ]:
# Load Shipments Dataset
shipments_df=pd.read_json('shipments.json')
shipments_df.head()

In [ ]:
# Load warehouses Dataset
warehouses_df=pd.read_json('warehouses.json')
warehouses_df.head()

#### 2.3 Load CSV Files

In [ ]:
# Load shipment_tracking Dataset
shipment_tracking_df=pd.read_csv('shipment_tracking.csv')
shipment_tracking_df.head()

In [ ]:
# Load routes Dataset
routes_df=pd.read_csv('routes.csv')
routes_df.head()

In [ ]:
# Load courier_staff Dataset
courier_staff_df=pd.read_csv('courier_staff.csv')
courier_staff_df.head()

In [ ]:
# Load costs Dataset
costs_df=pd.read_csv('costs.csv')
costs_df.head()

#### 2.4 Shipments Dataset Overview

In [ ]:
shipments_df.shape

In [ ]:
shipments_df.columns

In [ ]:
shipments_df.info()

In [ ]:
shipments_df.describe()

In [ ]:
shipments_df.describe(include=['O'])

- Shipments Dataset Overview
    + Number of records (rows): 70,000
    + Number of columns: 8
- Columns:
    + shipment_id, order_date, origin, destination, weight, courier_id, status, delivery_date
- Observations:
    + The **delivery_date** column contains null values for cancelled shipments, which will be handled during preprocessing.
    + shipments dataset serves as the primary fact table, and will be merged with:
        * **routes** (to determine origin-destination metrics)
        * **costs** (to calculate shipment costs)
        * **courier_staff** (to analyze courier performance)
        * **warehouses** (to analyze shipment origins and capacities)
        * **shipment_tracking** (to track shipment progress and delays)

#### 2.5 Warehouses Dataset Overview

In [ ]:
warehouses_df.shape

In [ ]:
warehouses_df.columns

In [ ]:
warehouses_df.info()

In [ ]:
warehouses_df.describe()

In [ ]:
warehouses_df.describe(include=['O'])

- Warehouses Dataset Overview:
    + Number of records (rows): 50
    + Number of columns: 4
- Observations:
    + All 50 entries are non-null, indicating complete data.
    + There are **50 unique warehouse IDs, 50 unique cities, and 31 unique states**, showing that some states have multiple warehouses.
    + The most frequent state in the dataset is **CT**, with **4 warehouses**.
    + The warehouses **dataset** can be merged with **shipments** using the **origin city** to analyze:
        * Warehouse utilization
        * Shipment distribution per warehouse
        * Potential bottlenecks or underutilized locations
        * state capacity utilization.

#### 2.6 Shipment_tracking Dataset Overview

In [ ]:
shipment_tracking_df.shape

In [ ]:
shipment_tracking_df.columns

In [ ]:
shipment_tracking_df.info()

In [ ]:
shipment_tracking_df.describe(include=['O'])

- Shipment Tracking Dataset Overview
    + Number of records (rows): 209,570
    + Number of columns: 4
- Observations:
    + **All columns are non-null**, ensuring complete tracking records.
    + There are **69,999 unique shipments**, meaning most shipments have multiple tracking events.
    + There are **6 unique status types**, showing the different stages of shipment progress.
    + There are 6,388 unique timestamps, with some timestamps repeated for multiple tracking events.
    + The most frequent status is Order Placed (70,000 occurrences).
    + The most frequent shipment ID is c2c0ddd0, appearing 7 times.
    + Can be merged with shipments to analyze:
        * Shipment progress and delays
        * Average time spent at each status stage
        * Tracking patterns for delivered vs cancelled shipments
    + Essential for building real-time tracking dashboards in Streamlit.

#### 2.7 Routes Dataset Overview

In [ ]:
routes_df.shape

In [ ]:
routes_df.columns

In [ ]:
routes_df.info()

In [ ]:
routes_df.describe()

In [ ]:
routes_df.describe(include=['O'])

- Routes Dataset Overview
    + Number of records (rows): 500
    + Number of columns: 5
- Observations:
All columns are non-null, indicating complete data.
    + There are **50 unique origin cities** and 50 unique destination cities.
    + The **most frequent origin is East David** (18 occurrences) and the **most frequent destination is Adammouth** (16 occurrences).
    + Distance (distance_km) ranges from 50.06 km to 1,996.10 km, with an average of ~1,053 km.
    + Average travel time (avg_time_hours) ranges from 1.1 hours to 47.8 hours, with a mean of ~23.3 hours.
    + Can be merged with shipments to analyze:
        * Route efficiency and distance metrics
        * Expected vs actual travel time (after merging with tracking data)
        * Bottleneck routes or long-distance shipments
        * Top routes by number of shipments
        * Average shipment distance/time per route

#### 2.8 Courier_staff Dataset Overview

In [ ]:
courier_staff_df.shape

In [ ]:
courier_staff_df.columns

In [ ]:
courier_staff_df.info()

In [ ]:
courier_staff_df.describe()

In [ ]:
courier_staff_df.describe(include=['O'])

- Courier Staff Dataset Overview
   + Number of records (rows): 1,000
   + Number of columns: 4
- Observations:
   + All 1,000 entries are non-null, indicating complete and clean data.
   + 1,000 unique courier IDs (each courier is unique)
   + 993 unique names (some names repeat, but IDs are unique)
   + 4 vehicle types
   + The most common vehicle type is Truck (261 couriers).
   + Rating Statistics:
      * Average rating: ~4.00
      * Minimum rating: 3.0
      * Maximum rating: 5.0
      * Most ratings fall between 3.5 and 4.5, indicating generally good performance.
   + It can be merged with shipments using courier_id to analyze:
      * Courier workload (number of shipments per courier)
      * Average rating vs delivery performance
      * Vehicle type distribution
      * Performance comparison across couriers
      * Top-performing couriers
      * Shipment count by vehicle type
      * Average rating distribution

#### 2.9 Costs Dataset Overview

In [ ]:
costs_df.shape

In [ ]:
costs_df.columns

In [ ]:
costs_df.info()

In [ ]:
costs_df.describe()

In [ ]:
costs_df.describe(include=['O'])

- Costs Dataset Overview
    + Number of records (rows): 70,000
    + Number of columns: 4
- Observations:
    + All 70,000 rows are non-null, indicating complete cost records.
    + shipment_id has:
        + 69,999 unique values
        + One shipment appears twice (frequency = 2), which may indicate:
            * Duplicate record
            * Data entry issue or cost split entry (needs validation)
    + Cost Statistics:
        + Labor cost is the highest average expense, followed by fuel, then miscellaneous.

    + This is a fact table directly linked to shipments via shipment_id.
        * Logical relationship:
            * shipments → costs = 1 : 1
        * Can be used to calculate:
            * Total shipment cost
            * Average cost per route
            * Cost per courier
            * Cost trends by weight or distance

### 3. Data Cleaning And Preprocessing

#### 3.1 Handling Missing Values

- Missing values are data points that are not recorded in the dataset. 
- Handling them is important to avoid errors in analysis, inaccurate insights, and broken dashboards.

##### 3.1.1 Shipments Dataset

In [ ]:
shipments_df.isnull().sum()

In [ ]:
plt.figure(figsize=(8,5))
sns.heatmap(shipments_df.isnull(),cbar=False)
plt.title("Heatmap of Missing Values in Shipments Dataset")
plt.xticks(rotation=45)
plt.show()

- The **delivery_date** column has **52,664 missing values** out of 70,000 shipments.
- All other columns are complete with no missing values.
- Null **delivery_date** corresponds to cancelled shipments or shipments not yet delivered.

In [ ]:
# Check if any 'Delivered' shipments have missing delivery_date
missing_delivered_date=shipments_df[(shipments_df['status']=='Delivered') & (shipments_df['delivery_date'].isnull())]
missing_delivered_date.shape

- This confirms that all “Delivered” shipments have a **delivery_date**, so the **status** and **delivery_date** columns are fully consistent.

##### 3.1.2 Warehouses Dataset

In [ ]:
warehouses_df.isnull().sum()

##### 3.1.3 Shipment_tracking Dataset

In [ ]:
shipment_tracking_df.isnull().sum()

##### 3.1.4 Routes Dataset

In [ ]:
routes_df.isnull().sum()

##### 3.1.5 Courier_staff Dataset

In [ ]:
courier_staff_df.isnull().sum()

##### 3.1.6 Costs Dataset

In [ ]:
costs_df.isnull().sum()

- All other datasets (**warehouses,shipment_tracking,routes,courier_staff,costs**) are complete. 
- No missing values

#### 3.2 Handling Duplicate Keys

- Duplicate keys occur when the same unique identifier appears more than once in a dataset. 
- They can cause **incorrect aggregations, join errors, and inconsistent analysis**, so it's important to identify and handle them.

In [ ]:
shipments_df[shipments_df.duplicated(subset='shipment_id',keep=False)]

- Both rows share the same shipment_id (c2c0ddd0) but have different order dates, origins, destinations, weights, couriers, and statuses.
- This indicates that the shipment_id is not unique in the raw data.
- Simply using shipment_id as a primary key would cause database integrity issues and lose valid shipment records.

##### Observation in Related Tables
- Shipment_tracking

In [ ]:
shipment_tracking_df[shipment_tracking_df['shipment_id']=='c2c0ddd0']

- There are **two separate dates** for this shipment_id: one **Cancelled (2026)** and one **Delivered (2025)**.
- This confirms the duplicate represents **two distinct shipments**, not a data entry error.

- Costs

In [ ]:
costs_df[costs_df['shipment_id']=='c2c0ddd0']

- **Costs** also differ for the two shipment records, further confirming these are **distinct shipments**.

- Implications
    + **shipment_id** cannot be used as a **primary key** for the fact table (shipments) in a star schema.
    + Directly using it as a key would **break referential integrity** for related tables (shipment_tracking, costs) because the database would not know which shipment a tracking or cost row belongs to.
    + These duplicates are a data quality issue at the source.

##### Solution Implemented to resolve this while preserving all shipment data:
- Step 1: Introduce a Surrogate Key in Shipments table

In [ ]:
# Reset index first to make sure it's clean
shipments_df = shipments_df.reset_index(drop=True)
# Add surrogate key based onindex
shipments_df.insert(0,'shipment_key',shipments_df.index+1)
# Verify the duplicate now has two different shipment_keys
shipments_df[shipments_df['shipment_id'] == 'c2c0ddd0'][['shipment_key', 'shipment_id', 'order_date', 'status']]

+ shipment_key → Primary key for shipments
+ shipment_id → Business ID (may have duplicates, just for reference)

- Step 2: Map Related Table Costs

In [ ]:
# Reset index first to make sure it's clean
costs_df = costs_df.reset_index(drop=True)
# Map shipment key to costs table
costs_df.insert(0,'shipment_key',shipments_df['shipment_key'])
# verify
costs_df[costs_df['shipment_id'] == 'c2c0ddd0']

In [1044]:
# confirm the row order actually matches:
(costs_df['shipment_id'] == shipments_df['shipment_id']).all()

- step 3: Map Related Table Shipment_tracking

In [1045]:
#convert dates for comparison
shipments_df['order_date'] = pd.to_datetime(shipments_df['order_date'])
shipment_tracking_df['timestamp'] = pd.to_datetime(shipment_tracking_df['timestamp'])
shipment_tracking_df.head()

   tracking_id shipment_id        status           timestamp
0            1    dc84cc15  Order Placed 2025-06-12 02:00:00
1            2    dc84cc15     Cancelled 2025-06-15 00:00:00
2            3    ca536e73  Order Placed 2025-06-27 02:00:00
3            4    ca536e73     Cancelled 2025-06-28 00:00:00
4            5    704fa19e  Order Placed 2025-09-09 03:00:00

In [1046]:
# Find duplicate_ids in shipments
duplicate_ids=shipments_df[shipments_df.duplicated(subset='shipment_id',keep=False)]['shipment_id'].unique()

In [1047]:
# Separate duplicate from non-duplicates in shipment_tracking
tracking_normal=shipment_tracking_df[~shipment_tracking_df['shipment_id'].isin(duplicate_ids)].copy()
tracking_dupes=shipment_tracking_df[shipment_tracking_df['shipment_id'].isin(duplicate_ids)].copy()

In [1048]:
# For normal rows — simple merge on shipment_id only
normal_lookup=shipments_df[~(shipments_df['shipment_id'].isin(duplicate_ids))][['shipment_id','shipment_key']]
tracking_normal=tracking_normal.merge(normal_lookup,on='shipment_id',how='left')

In [1049]:
# For duplicate rows — merge on shipment_id + year
dupe_lookup=shipments_df[shipments_df['shipment_id'].isin(duplicate_ids)][['shipment_id','shipment_key','order_date']].copy()
dupe_lookup['year']=dupe_lookup['order_date'].dt.year

In [1050]:
tracking_dupes['year']=tracking_dupes['timestamp'].dt.year

In [1051]:
tracking_dupes=tracking_dupes.merge(
    dupe_lookup[['shipment_id','shipment_key','year']],
    on=['shipment_id','year'],
    how='left')
tracking_dupes.drop(columns='year',inplace=True)

In [1052]:
# combine back
shipment_tracking_df=pd.concat([tracking_normal,tracking_dupes],ignore_index=True)
shipment_tracking_df=shipment_tracking_df.sort_values('tracking_id').reset_index(drop=True)
shipment_tracking_df.head()

   tracking_id shipment_id        status           timestamp  shipment_key
0            1    dc84cc15  Order Placed 2025-06-12 02:00:00             1
1            2    dc84cc15     Cancelled 2025-06-15 00:00:00             1
2            3    ca536e73  Order Placed 2025-06-27 02:00:00             2
3            4    ca536e73     Cancelled 2025-06-28 00:00:00             2
4            5    704fa19e  Order Placed 2025-09-09 03:00:00             3

- Verifying everything merged properly

1. Check for NULL shipment_key

In [1053]:
shipment_tracking_df['shipment_key'].isna().sum()

np.int64(0)

- No Null values in column **shipment_key**

2. Check For Duplicate tracking_id

In [1054]:
shipment_tracking_df['tracking_id'].duplicated().sum()

np.int64(0)

- No dupplicated rows

3. Random Spot Check

In [1055]:
ship_id = 'c2c0ddd0'
shipments_df[shipments_df['shipment_id'] == ship_id]

,shipment_key,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
4553,4554,c2c0ddd0,2026-01-31,Brookeburgh,West Jared,5.89,995299ac,Cancelled,None
8106,8107,c2c0ddd0,2025-04-09,South Brianside,East Johnshire,33.55,1cddbd0e,Delivered,2025-04-16

In [1056]:
shipment_tracking_df[shipment_tracking_df['shipment_id'] == ship_id]

,tracking_id,shipment_id,status,timestamp,shipment_key
13702,13703,c2c0ddd0,Order Placed,2026-01-31 02:00:00,4554
13703,13704,c2c0ddd0,Cancelled,2026-02-02 00:00:00,4554
24294,24295,c2c0ddd0,Order Placed,2025-04-09 03:00:00,8107
24295,24296,c2c0ddd0,Picked Up,2025-04-11 00:00:00,8107
24296,24297,c2c0ddd0,In Transit,2025-04-12 00:00:00,8107
24297,24298,c2c0ddd0,Out for Delivery,2025-04-16 07:00:00,8107
24298,24299,c2c0ddd0,Delivered,2025-04-16 12:00:00,8107

- shipment_key exists
- tracking rows point to correct shipment_key and the status are clear

4. Final Referential Integrity 
    - Every Shipment Has At Least One Tracking Event

In [1057]:
set(shipment_tracking_df['shipment_key']).difference(
    set(shipments_df['shipment_key'])
)

set()

In [1058]:
#Now it is safe to drop 'shipment_id' in shipment_tracking
shipment_tracking_df.drop(columns='shipment_id',inplace=True)
shipment_tracking_df.head()

   tracking_id        status           timestamp  shipment_key
0            1  Order Placed 2025-06-12 02:00:00             1
1            2     Cancelled 2025-06-15 00:00:00             1
2            3  Order Placed 2025-06-27 02:00:00             2
3            4     Cancelled 2025-06-28 00:00:00             2
4            5  Order Placed 2025-09-09 03:00:00             3

In [1059]:
# drop shipment_id in costs 
costs_df.drop(columns='shipment_id',inplace=True)
costs_df.head()

   shipment_key  fuel_cost  labor_cost  misc_cost
0             1      61.08       27.24      20.75
1             2      13.74       65.13      17.63
2             3      72.68       39.47      16.84
3             4      53.69       23.23      33.16
4             5      90.24      107.29      14.73

#### 3.3 Fixing Data Types
- Ensuring proper data types prevents errors in calculations, filtering, and database ingestion.

##### 3.3.1 Shipments

In [1060]:
shipments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shipment_key   70000 non-null  int64
 1   shipment_id    70000 non-null  object
 2   order_date     70000 non-null  datetime64[ns]
 3   origin         70000 non-null  object
 4   destination    70000 non-null  object
 5   weight         70000 non-null  float64
 6   courier_id     70000 non-null  object
 7   status         70000 non-null  object
 8   delivery_date  17336 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 4.8+ MB

In [1061]:
# Convert date columns to datetime
shipments_df['delivery_date']=pd.to_datetime(shipments_df['delivery_date'])
shipments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shipment_key   70000 non-null  int64
 1   shipment_id    70000 non-null  object
 2   order_date     70000 non-null  datetime64[ns]
 3   origin         70000 non-null  object
 4   destination    70000 non-null  object
 5   weight         70000 non-null  float64
 6   courier_id     70000 non-null  object
 7   status         70000 non-null  object
 8   delivery_date  17336 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(5)
memory usage: 4.8+ MB

##### 3.3.2 Shipment Tracking

In [1062]:
shipment_tracking_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209570 entries, 0 to 209569
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   tracking_id   209570 non-null  int64
 1   status        209570 non-null  object
 2   timestamp     209570 non-null  datetime64[ns]
 3   shipment_key  209570 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 6.4+ MB

In [1063]:
shipment_tracking_df['status'].unique()

array(['Order Placed', 'Cancelled', 'Picked Up', 'In Transit',
       'Out for Delivery', 'Delivered'], dtype=object)

##### 3.3.3 Shipments Tracking

In [1064]:
shipments_df['status'].unique()

array(['Cancelled', 'Delivered', 'In Transit', 'Pending'], dtype=object)

##### 3.3.4 Courier_staff Vehicle Types

In [1065]:
courier_staff_df['vehicle_type'].unique()

array(['Van', 'Truck', 'Car', 'Bike'], dtype=object)

##### 3.3.5 Shipments and warehouses City Standardization

In [1066]:
shipments_df['origin'] = shipments_df['origin'].str.strip().str.title()
shipments_df['destination'] = shipments_df['destination'].str.strip().str.title()

warehouses_df['city'] = warehouses_df['city'].str.strip().str.title()
warehouses_df['state'] = warehouses_df['state'].str.strip().str.upper()  # states in uppercase for consistency

##### 3.3.6 Referential Integrity Check

In [1067]:
shipments_df.loc[~shipments_df['origin'].isin(warehouses_df['city'])]

Empty DataFrame
Columns: [shipment_key, shipment_id, order_date, origin, destination, weight, courier_id, status, delivery_date]
Index: []

In [1068]:
shipments_df.loc[~shipments_df['destination'].isin(warehouses_df['city'])]

Empty DataFrame
Columns: [shipment_key, shipment_id, order_date, origin, destination, weight, courier_id, status, delivery_date]
Index: []

- Checking every shipment origin/destination must exist in the warehouse master table.

##### 3.3.7 Delivered Shipments Must Have Delivered Event

In [1069]:
# Get all shipments marked as 'Delivered' in the shipments table
delivered_shipments=shipments_df.loc[shipments_df['status']=='Delivered','shipment_key']
# Get all shipment_keys that have a 'Delivered' event in shipment_tracking
delivered_events=shipment_tracking_df.loc[shipment_tracking_df['status']=='Delivered','shipment_key']
# Check if any delivered shipment is missing a delivered event
set(delivered_shipments).difference(set(delivered_events))

set()

- Ensures every shipment marked as 'Delivered' in the shipments table has a corresponding 'Delivered' event in the shipment_tracking table.
- Any mismatch indicates missing tracking data or data entry issues.

##### 3.3.8 Routes Standardization

In [1070]:
routes_df['origin'] = routes_df['origin'].str.strip().str.title()
routes_df['destination'] = routes_df['destination'].str.strip().str.title()

In [1071]:
# Create sets of valid routes
valid_routes = set(zip(routes_df['origin'], routes_df['destination']))

In [1072]:
# Create shipment route pairs
shipment_routes = list(zip(shipments_df['origin'], shipments_df['destination']))

In [1073]:
# Find invalid shipment routes
invalid_routes = [pair for pair in shipment_routes if pair not in valid_routes]
invalid_routes

[]

- all shipments match a valid route

### 4. Database Schema Design

- Fact tables (shipments, costs, shipment_tracking) are clean
- Dimension tables courier_staff has phyical relationship with shipments table
- Next is Warehouse and routes tables

#### 4.1 Warehouses

- Create warehouse_key in warehouses_df

In [1074]:
# 1. Create  Surrogate Key In Warehouses
warehouses_df = warehouses_df.reset_index(drop=True)
warehouses_df.insert(0, 'warehouse_key', warehouses_df.index + 1)
warehouses_df.head()

   warehouse_key warehouse_id                  city state  capacity
0              1     647a65d8     North Claudiatown    SC      9821
1              2     8bdbd012            East David    MT      1138
2              3     cfcbd086          North Justin    ND      6019
3              4     3bff4497    Port Sandrachester    CT      3300
4              5     6767e7a4  North Williamchester    SD      6822

In [1075]:
# 2. Check For Duplicate Cities In Warehouses
warehouses_df.duplicated(subset=['city']).sum()

np.int64(0)

- Add warehouse_key as FK in shipments

In [1076]:
# Simple merge for origin warehouse
shipments_df = shipments_df.merge(
    warehouses_df[['warehouse_key', 'city']],
    left_on='origin',
    right_on='city',
    how='left'
).drop(columns=['city']).rename(columns={'warehouse_key': 'origin_warehouse_key'})

In [1077]:

# Simple merge for destination warehouse
shipments_df = shipments_df.merge(
    warehouses_df[['warehouse_key', 'city']],
    left_on='destination',
    right_on='city',
    how='left'
).drop(columns=['city']).rename(columns={'warehouse_key': 'destination_warehouse_key'})

- verifying after merging

In [1078]:
shipments_df['destination_warehouse_key'].isna().sum()

np.int64(0)

In [1079]:
shipments_df['origin_warehouse_key'].isna().sum()

np.int64(0)

In [1080]:
shipments_df['origin_warehouse_key'].notna().sum()

np.int64(70000)

In [1081]:
shipments_df['destination_warehouse_key'].notna().sum()

np.int64(70000)

- warehouses_df: warehouse_key must be unique

In [1082]:
warehouses_df['warehouse_key'].nunique() == len(warehouses_df)

True

#### 4.2 Routes

-  Create route_key in routes_df

In [1083]:
# Check what's different between duplicate route pairs
dup_origins = routes_df[routes_df.duplicated(subset=['origin','destination'], keep=False)]
print(dup_origins.sort_values(['origin','destination']).head(20))

     route_id            origin       destination  distance_km  avg_time_hours
226  c6485b2b      Andersonfurt          Ginafort       905.75            32.0
459  1c24fb0f      Andersonfurt          Ginafort       902.18             2.4
174  1b70b531       Brookeburgh        West Jared      1058.47            47.5
488  876b523e       Brookeburgh        West Jared       972.38             9.5
83   a45c6220        Carolmouth       New Colleen       142.05            34.9
224  c2e20179        Carolmouth       New Colleen      1855.75            26.4
21   dca50f1a  Christinechester        South John      1628.49            40.0
42   2c3a79b2  Christinechester        South John       643.90             8.2
246  12b0773b  Christinechester  West Tarachester      1455.22            45.5
320  12bd4e04  Christinechester  West Tarachester       828.43            23.3
30   3b2ab19e          Darinton        West Jared       524.36             5.3
397  ee1374dc          Darinton        West Jared       608.96             5.2
28   f8991b81          Darinton       West Wesley        70.43            35.5
250  eed607ce          Darinton       West Wesley      1091.52             2.5
483  7854b3da          Darinton       West Wesley       793.37            41.2
12   819e0c6f        Davidshire        East David       462.96            36.3
118  3be86faa        Davidshire        East David       771.16             5.5
258  354baf69        Davidshire        East David      1916.63            19.9
264  540446ca        East David     East Victoria       929.35            17.8
310  aeaf6ba7        East David     East Victoria      1853.67            12.6

In [1084]:
# 1. Create surrogate key in routes_df 
routes_df = routes_df.reset_index(drop=True)
routes_df.insert(0, 'route_key', routes_df.index + 1)

In [1085]:

# 2. Pick best route per origin-destination pair 
best_routes = routes_df.sort_values('avg_time_hours').drop_duplicates(
    subset=['origin', 'destination'],
    keep='first'
)

In [1086]:

# 3. Merge into shipments 
shipments_df = shipments_df.merge(
    best_routes[['route_key', 'origin', 'destination']],
    on=['origin', 'destination'],
    how='left',
    validate='many_to_one'
)
routes_df.head()

,route_key,route_id,origin,destination,distance_km,avg_time_hours
0,1,fe423f38,East Victoria,South Raymond,1016.50,44.2
1,2,080ff620,Mooreshire,Davidshire,58.30,45.3
2,3,aa6e4a5f,Mooreshire,South Raymond,977.98,42.4
3,4,3aa7af93,Kimfort,East Johnshire,691.84,35.7
4,5,39913248,Tiffanyton,East David,1836.43,24.4

- Verifying after merging

In [1087]:
shipments_df['route_key'].isna().sum()

np.int64(0)

- routes_df: route_key must be unique

In [1088]:
routes_df['route_key'].nunique() == len(routes_df)

True

In [1089]:
valid_routes = set(zip(routes_df['origin'], routes_df['destination']))
shipment_routes = set(zip(shipments_df['origin'], shipments_df['destination']))
invalid_routes = shipment_routes - valid_routes
invalid_routes  # should ideally be empty

set()

In [1090]:
missing_origins = set(shipments_df['origin']) - set(warehouses_df['city'])
missing_destinations = set(shipments_df['destination']) - set(warehouses_df['city'])

missing_origins, missing_destinations  # ideally should be empty sets

(set(), set())

In [1091]:
shipments_df['shipment_key'].nunique() == len(shipments_df)

True

In [1092]:
shipments_df[['shipment_key', 'shipment_id', 'origin', 'destination', 'route_key', 'origin_warehouse_key','destination_warehouse_key']].head(10)

,shipment_key,shipment_id,origin,destination,route_key,origin_warehouse_key,destination_warehouse_key
0,1,dc84cc15,North Dawnfort,Ginafort,54,39,37
1,2,ca536e73,North Williamchester,Christinechester,18,5,10
2,3,704fa19e,New Colleen,West Jared,6,49,31
3,4,aad8a598,South Ashleystad,Jonestown,8,18,28
4,5,e120d4ba,Darinton,West Jared,398,15,31
5,6,9ce359e4,Brookeburgh,North Trevorbury,410,27,24
6,7,b3e4dbad,North Arthur,South Ashleystad,470,7,18
7,8,ce2b8607,New Colleen,Tiffanyton,220,49,29
8,9,ff237e66,East David,North Williamchester,112,2,5
9,10,a5eb45cd,South Raymond,South Brianside,392,41,9

In [1093]:
shipments_df = shipments_df.drop(columns=['origin', 'destination'])
shipments_df

,shipment_key,shipment_id,order_date,weight,courier_id,status,delivery_date,origin_warehouse_key,destination_warehouse_key,route_key
0,1,dc84cc15,2025-06-12,43.52,b554e6a4,Cancelled,NaT,39,37,54
1,2,ca536e73,2025-06-27,19.31,9b44d9ca,Cancelled,NaT,5,10,18
2,3,704fa19e,2025-09-09,27.97,f8c3e908,Delivered,2025-09-13,49,31,6
3,4,aad8a598,2025-07-25,18.74,0de3fc1b,Cancelled,NaT,18,28,8
4,5,e120d4ba,2026-01-06,39.30,44def2f4,In Transit,NaT,15,31,398
...,...,...,...,...,...,...,...,...,...,...
69995,69996,33f9c844,2025-08-09,6.66,09470953,Cancelled,NaT,31,9,361
69996,69997,6ca403d1,2025-09-05,16.78,353f1b39,Cancelled,NaT,20,34,4
69997,69998,59a42fb4,2025-05-29,6.97,acb241ba,Cancelled,NaT,48,4,463
69998,69999,3cfb7692,2026-02-18,49.57,409aec25,Pending,NaT,18,49,239
69999,70000,f212e1c9,2025-11-14,33.21,d1370c82,In Transit,NaT,29,22,443

#### 4.3 ER diagram of the logistics database.

- ER Diagram Logistics.png file is attached in the same folder

 
- **Shipments**: Fact table, `shipment_key` as PK; `shipment_id` is the business key.  
- **Costs**: Secondary Fact table,Shipments (1) ──────── (1) Costs 
- **Shipment Tracking**: Event fact table,Shipments (1) ────────< Shipment_Tracking (M)  
- **Courier Staff**: Dimension table,Courier_Staff (1) ────────< Shipments (M) 
- **Routes**: Dimension table, Routes (1) ────────< Shipments (M) 
- **Warehouses**: Dimension table, Warehouses (1) ────────< Shipments (M)

### 5. Creating MySQL Tables and Inserting Data

#### 5.1 Setup MySQL Connection

- Establishing the database connection

In [1094]:
conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="logistics"
)

#### 5.2 Create Dimension Tables

````
CREATE TABLE courier_staff (
	courier_id VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50),
	rating DECIMAL(3,1),
	vehicle_type VARCHAR(50)
); 

CREATE TABLE warehouses (
	warehouse_key INT PRIMARY KEY,
	warehouse_id VARCHAR(50),
	city VARCHAR(100),
    state VARCHAR(10),
    capacity INT
);

CREATE TABLE routes (
	route_key int PRIMARY KEY,
	route_id vARCHAR(50),
	origin VARCHAR(50),
	destination VARCHAR(50),
	distance_km DECIMAL(10,2),
	avg_time_hours DECIMAL(5,2)
);

#### 5.3 Create Fact Tables

````
CREATE TABLE shipments (
	shipment_key INT PRIMARY KEY,
	shipment_id VARCHAR(50),
	order_date DATE,
	delivery_date DATE,
	weight DECIMAL(10,2),
	courier_id varchar(50),
	status varchar(50),
	origin_warehouse_key INT,
	destination_warehouse_key INT,
	route_key INT,
	FOREIGN KEY (courier_id) REFERENCES courier_staff(courier_id),
	FOREIGN KEY (origin_warehouse_key) REFERENCES warehouses(warehouse_key),
	FOREIGN KEY (destination_warehouse_key) REFERENCES warehouses(warehouse_key),
	FOREIGN KEY (route_key) REFERENCES routes(route_key)
);
CREATE TABLE costs (
	shipment_key INT PRIMARY KEY,
	fuel_cost DECIMAL(15,2),
	labor_cost DECIMAL(15,2),
	misc_cost DECIMAL(15,2),
	FOREIGN KEY (shipment_key) REFERENCES shipments(shipment_key)
);

CREATE TABLE shipment_tracking (
	tracking_id INT PRIMARY KEY,
	shipment_key INT,
	status VARCHAR(50),
	timestamp DATETIME,
	FOREIGN KEY (shipment_key) REFERENCES shipments(shipment_key)
);

In [1095]:
# Creating a cursor object
cursor=conn.cursor()

In [1096]:
cursor.execute("SHOW TABLES;")

In [1097]:
# Table Creation Verification
tables = cursor.fetchall()
tables

[('costs',),
 ('courier_staff',),
 ('routes',),
 ('routes_backup',),
 ('shipment_tracking',),
 ('shipments',),
 ('warehouses',)]

In [1098]:
cursor.close()

True

In [1099]:
#Create a SQLAlchemy engine to connect to the MySQL database
engine = create_engine(
    "mysql+mysqlconnector://root:root@localhost/logistics"
)

#### 5.4 INSERT Dimension tables FIRST (parent tables — no FKs)

- courier_staff

In [1100]:
#Convert the Pandas DataFrame to a format for MySQL table insertion
#courier_staff_df.to_sql('courier_staff',con=engine,if_exists='append',index=False)

- warehouses table

In [1101]:
#warehouses_df.to_sql('warehouses',con=engine,if_exists='append',index=False)

- routes table

In [1102]:
#routes_df.to_sql('routes',con=engine,if_exists='append',index=False)

#### 5.5 SECOND Central Fact  (depends on all 3 dimensions above)

- shipments table

In [1103]:
#shipments_df.to_sql('shipments',con=engine,if_exists='append',index=False)

#### 5.6 LAST Child tables  (depend on shipments)

- costs table

In [1104]:
#costs_df.to_sql('costs',con=engine,if_exists='append',index=False)

- shipment_tracking

In [1105]:
#shipment_tracking_df.to_sql('shipment_tracking',con=engine,if_exists='append',index=False)

### 6. Database Validation and Integrity Checks

#### 6.1 Table Creation Verification

In [1106]:
conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="logistics"
)
cursor=conn.cursor()
cursor.execute("SHOW TABLES;")
tables=cursor.fetchall()

print("The Table in Logistics Database:\n")
tables_list = [t[0] for t in tables]
print(tables_list)

The Table in Logistics Database:

['costs', 'courier_staff', 'routes', 'routes_backup', 'shipment_tracking', 'shipments', 'warehouses']

    - SHOW TABLES;
    - All six tables were present in the logistics database

#### 6.2 Row Count Validation

In [1107]:
for x in tables_list:
    cursor.execute(f"SELECT COUNT(*) FROM {x};")
    print(f"No of Rows in table {x} is {(cursor.fetchone())[0]}")

No of Rows in table costs is 70000
No of Rows in table courier_staff is 1000
No of Rows in table routes is 500
No of Rows in table routes_backup is 500
No of Rows in table shipment_tracking is 209570
No of Rows in table shipments is 70000
No of Rows in table warehouses is 50

+ The number of shipment records matched the expected count from the cleaned dataset.

#### 6.3 Referential Integrity Enforcement
- SHOW CREATE TABLE shipments;
- The output confirmed that the following foreign key constraints were enforced:
    + courier_id → courier_staff(courier_id)
    + origin_warehouse_key → warehouses(warehouse_key)
    + destination_warehouse_key → warehouses(warehouse_key)
    + route_key → routes(route_key)